package com.csr.donor.utils

object ServiceConstants {
    const val MAIN_SERVICE_IS_STARTED = "MAIN_SERVICE_IS_STARTED"
    const val MAIN_SERVICE_PINGING = "MAIN_SERVICE_PINGING"

    const val SOUND_COMPOSER_DATA = "SOUND_COMPOSER_DATA"
    const val SOUND_COMPOSER_SOUND_STATE_BROAD_CAST = "SOUND_COMPOSER_SOUND_STATE_BROAD_CAST"
    const val ACTIVE_SOUND_REMIX_LIST = "ACTIVE_SOUND_REMIX_LIST"
    const val IS_ALL_SOUNDS_ARE_PLAYING = "IS_ALL_SOUNDS_ARE_PLAYING"
    const val ACTIVE_SOUND_REMIX_ID_LIST = "ACTIVE_SOUND_REMIX_ID_LIST"
    const val IN_ACTIVE_COMPOSE_SOUND_LIST = "IN_ACTIVE_COMPOSE_SOUND_LIST"
    const val SOUND_COMPOSE_IS_PREPARING = "IN_ACTIVE_COMPOSE_SOUND_LIST"

    const val MAIN_SOUND_SERVICE_DATA_BROADCAST = "MAIN_SOUND_SERVICE_DATA_BROADCAST"
    const val MAIN_SOUND_SERVICE_PINGING_BROADCAST = "MAIN_SOUND_SERVICE_PINGING_BROADCAST"
    const val MAIN_SOUND_SERVICE_IS_PREPARING = "MAIN_SOUND_SERVICE_IS_PREPARING"
    const val SOUND_CATEGORY_DATA = "SOUND_CATEGORY_DATA"
    const val SINGLE_SOUND_DATA = "SINGLE_SOUND_DATA"
    const val TOTAL_DURATION = "TOTAL_DURATION"
    const val CURRENT_POSITION = "CURRENT_POSITION"
    const val CURRENT_SOUND_ID= "CURRENT_SOUND_ID"
    const val CURRENT_SOUND_NAME= "CURRENT_SOUND_NAME"
    const val CURRENT_SOUND_LOGO= "CURRENT_SOUND_LOGO"
    const val CURRENT_SOUND_CATEGORY= "CURRENT_SOUND_CATEGORY"
    const val IS_PLAYING = "IS_PLAYING"



}